# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create({firstname: "Leo", lastname: "Zago", city: "Brooklyn", state: "NY", email: "veranyc+leo@gmail.com", password: "cat"})

Artist.create([{name: "LCD Soundsystem"}, {name: "The White Stripes"}, {name: "The Cure"}, {name: "Beck"}, {name: "Beastie Boys"}])

Event.create([
  {artists_id: 1, venue: "Brooklyn Steel", city: "Brooklyn", state: "NY", country: "USA"},
  {artists_id: 2, venue: "Bowery Ballroom", city: "New York", state: "NY", country: "USA"},
  {artists_id: 3, venue: "Madison Square Garden", city: "New York", state: "NY", country: "USA"},
  {artists_id: 4, venue: "Sony Centre for the Performing Arts", city: "Toronto", country: "Canada"},
  {artists_id: 5, venue: "Hiro Ballroom", city: "New York", state: "NY", country: "USA"}
  ])

Setlist.create([{events_id: 1},{events_id: 2},{events_id: 3},{events_id: 4},{events_id: 5}])

Song.create([
  {artists_id: 1, title: "Us v Them"},
  {artists_id: 1, title: "Daft Punk Is Playing at My House"},
  {artists_id: 1, title: "I Can Change"},
  {artists_id: 1, title: "Get Innocuous!"},
  {artists_id: 1, title: "You Wanted a Hit"},
  {artists_id: 1, title: "Tribulations"},
  {artists_id: 1, title: "Movement"},
  {artists_id: 1, title: "Someone Great"},
  {artists_id: 1, title: "Home"},
  {artists_id: 1, title: "New York, I Love You But You're Bringing Me Down"},
  {artists_id: 1, title: "Emotional Haircut"},
  {artists_id: 1, title: "Tonite"},
  {artists_id: 1, title: "Call the Police"},
  {artists_id: 1, title: "American Dream"},
  {artists_id: 1, title: "Dance Yrself Clean"},
  {artists_id: 1, title: "All My Friends"},
  {artists_id: 2, title: "Dead Leaves and the Dirty Ground"},
  {artists_id: 2, title: "When I Hear My Name"},
  {artists_id: 2, title: "Death Letter"},
  {artists_id: 2, title: "Motherless Children"},
  {artists_id: 2, title: "Little Bird"},
  {artists_id: 2, title: "I Think I Smell a Rat"},
  {artists_id: 2, title: "Jolene"},
  {artists_id: 2, title: "I'm Finding It Harder to Be a Gentleman"},
  {artists_id: 2, title: "Hotel Yorba"},
  {artists_id: 2, title: "She Comes in Colors"},
  {artists_id: 2, title: "Cannon"},
  {artists_id: 2, title: "Lovesick"},
  {artists_id: 2, title: "Expecting"},
  {artists_id: 2, title: "The Object of my Affection"},
  {artists_id: 2, title: "Let's Do It"},
  {artists_id: 2, title: "Lord, Send Me an Angel"},
  {artists_id: 2, title: "Fell in Love With a Girl"},
  {artists_id: 2, title: "St. James Infirmary"},
  {artists_id: 2, title: "Baby Blue"},
  {artists_id: 2, title: "Astro"},
  {artists_id: 2, title: "Jack the Ripper"},
  {artists_id: 2, title: "We're Going to Be Friends"},
  {artists_id: 2, title: "Jimmy the Exploder"},
  {artists_id: 2, title: "I Fought Piranhas"},
  {artists_id: 2, title: "You're Pretty Good Looking (For a Girl)"},
  {artists_id: 2, title: "Hello Operator"},
  {artists_id: 2, title: "Screwdriver"},
  {artists_id: 2, title: "Boll Weevil"},
  {artists_id: 3, title: "Pictures of You"},
  {artists_id: 3, title: "This Twilight Garden"},
  {artists_id: 3, title: "A Night Like This"},
  {artists_id: 3, title: "The End of the World"},
  {artists_id: 3, title: "Lovesong"},
  {artists_id: 3, title: "Primary"},
  {artists_id: 3, title: "If Only Tonight We Could Sleep"},
  {artists_id: 3, title: "All I Want"},
  {artists_id: 3, title: "Push"},
  {artists_id: 3, title: "In Between Days"},
  {artists_id: 3, title: "Just Like Heaven"},
  {artists_id: 3, title: "From the Edge of the Deep Green Sea"},
  {artists_id: 3, title: "The Hanging Garden"},
  {artists_id: 3, title: "One Hundred Years"},
  {artists_id: 3, title: "It Can Never Be the Same"},
  {artists_id: 3, title: "Pornography"},
  {artists_id: 3, title: "Dressing Up"},
  {artists_id: 3, title: "The Snakepit"},
  {artists_id: 3, title: "Burn"},
  {artists_id: 3, title: "Lullaby"},
  {artists_id: 3, title: "Never Enough"},
  {artists_id: 3, title: "Fascination Street"},
  {artists_id: 3, title: "Wrong Number"},
  {artists_id: 3, title: "The Lovecats"},
  {artists_id: 3, title: "Let's Go to Bed"},
  {artists_id: 3, title: "Close to Me"},
  {artists_id: 3, title: "Why Can't I Be You?"},
  {artists_id: 3, title: "Boy's Don't Cry"},
  {artists_id: 4, title: "Devil's Haircut"},
  {artists_id: 4, title: "Black Tambourine"},
  {artists_id: 4, title: "Soul of A Man"},
  {artists_id: 4, title: "The New Pollution"},
  {artists_id: 4, title: "Loser"},
  {artists_id: 4, title: "Hotwax"},
  {artists_id: 4, title: "One Food in the Grave"},
  {artists_id: 4, title: "Hell Yes"},
  {artists_id: 4, title: "Modern Guilt"},
  {artists_id: 4, title: "Think I'm in Love"},
  {artists_id: 4, title: "Paper Tiger"},
  {artists_id: 4, title: "Blue Moon"},
  {artists_id: 4, title: "Say Goodbye"},
  {artists_id: 4, title: "Blackbird Chain"},
  {artists_id: 4, title: "Country Down"},
  {artists_id: 4, title: "Waking Light"},
  {artists_id: 4, title: "Girl"},
  {artists_id: 4, title: "E-Pro"},
  {artists_id: 4, title: "Sexx Laws"},
  {artists_id: 4, title: "Where It's At"},
  {artists_id: 5, title: "Slow and Low"},
  {artists_id: 5, title: "Body Movin'"},
  {artists_id: 5, title: "Sure Shot"},
  {artists_id: 5, title: "Triple Trouble"},
  {artists_id: 5, title: "Shake Your Rump"},
  {artists_id: 5, title: "Pass The Mic"},
  {artists_id: 5, title: "Egg Man"},
  {artists_id: 5, title: "Hello Brooklyn"},
  {artists_id: 5, title: "No Sleep Till Brooklyn"},
  {artists_id: 5, title: "Root Down"},
  {artists_id: 5, title: "Ch-Check It Out"},
  {artists_id: 5, title: "Three MC's and One DJ"},
  {artists_id: 5, title: "Intergalactic"},
  {artists_id: 5, title: "So What'cha Want"}

  ])

  Setlist_song.create([
    {song_id: 1, setlist_id: 1},
    {song_id: 2, setlist_id: 1},
    {song_id: 3, setlist_id: 1},
    {song_id: 4, setlist_id: 1},
    {song_id: 5, setlist_id: 1},
    {song_id: 6, setlist_id: 1},
    {song_id: 7, setlist_id: 1},
    {song_id: 8, setlist_id: 1},
    {song_id: 9, setlist_id: 1},
    {song_id: 10, setlist_id: 1},
    {song_id: 11, setlist_id: 1},
    {song_id: 12, setlist_id: 1},
    {song_id: 13, setlist_id: 1},
    {song_id: 14, setlist_id: 1},
    {song_id: 15, setlist_id: 1},
    {song_id: 16, setlist_id: 1},
    {song_id: 17, setlist_id: 2},
    {song_id: 18, setlist_id: 2},
    {song_id: 19, setlist_id: 2},
    {song_id: 20, setlist_id: 2},
    {song_id: 21, setlist_id: 2},
    {song_id: 22, setlist_id: 2},
    {song_id: 23, setlist_id: 2},
    {song_id: 24, setlist_id: 2},
    {song_id: 25, setlist_id: 2},
    {song_id: 26, setlist_id: 2},
    {song_id: 27, setlist_id: 2},
    {song_id: 28, setlist_id: 2},
    {song_id: 29, setlist_id: 2},
    {song_id: 30, setlist_id: 2},
    {song_id: 31, setlist_id: 2},
    {song_id: 32, setlist_id: 2},
    {song_id: 33, setlist_id: 2},
    {song_id: 34, setlist_id: 2},
    {song_id: 35, setlist_id: 2},
    {song_id: 36, setlist_id: 2},
    {song_id: 37, setlist_id: 2},
    {song_id: 38, setlist_id: 2},
    {song_id: 39, setlist_id: 2},
    {song_id: 40, setlist_id: 2},
    {song_id: 41, setlist_id: 2},
    {song_id: 42, setlist_id: 2},
    {song_id: 43, setlist_id: 2},
    {song_id: 44, setlist_id: 2},
    {song_id: 45, setlist_id: 2},
    {song_id: 46, setlist_id: 2},
    {song_id: 47, setlist_id: 2},
    {song_id: 48, setlist_id: 3},
    {song_id: 49, setlist_id: 3},
    {song_id: 50, setlist_id: 3},
    {song_id: 51, setlist_id: 3},
    {song_id: 52, setlist_id: 3},
    {song_id: 53, setlist_id: 3},
    {song_id: 54, setlist_id: 3},
    {song_id: 55, setlist_id: 3},
    {song_id: 56, setlist_id: 3},
    {song_id: 57, setlist_id: 3},
    {song_id: 58, setlist_id: 3},
    {song_id: 59, setlist_id: 3},
    {song_id: 60, setlist_id: 3},
    {song_id: 61, setlist_id: 3},
    {song_id: 62, setlist_id: 3},
    {song_id: 63, setlist_id: 3},
    {song_id: 64, setlist_id: 3},
    {song_id: 65, setlist_id: 3},
    {song_id: 66, setlist_id: 3},
    {song_id: 67, setlist_id: 3},
    {song_id: 68, setlist_id: 3},
    {song_id: 69, setlist_id: 3},
    {song_id: 70, setlist_id: 3},
    {song_id: 71, setlist_id: 3},
    {song_id: 72, setlist_id: 3},
    {song_id: 73, setlist_id: 3},
    {song_id: 74, setlist_id: 3},
    {song_id: 75, setlist_id: 3},
    {song_id: 76, setlist_id: 3},
    {song_id: 77, setlist_id: 3},
    {song_id: 78, setlist_id: 4},
    {song_id: 79, setlist_id: 4},
    {song_id: 80, setlist_id: 4},
    {song_id: 81, setlist_id: 4},
    {song_id: 82, setlist_id: 4},
    {song_id: 83, setlist_id: 4},
    {song_id: 84, setlist_id: 4},
    {song_id: 85, setlist_id: 4},
    {song_id: 86, setlist_id: 4},
    {song_id: 87, setlist_id: 4},
    {song_id: 88, setlist_id: 4},
    {song_id: 89, setlist_id: 4},
    {song_id: 90, setlist_id: 4},
    {song_id: 91, setlist_id: 4},
    {song_id: 92, setlist_id: 4},
    {song_id: 93, setlist_id: 4},
    {song_id: 94, setlist_id: 4},
    {song_id: 95, setlist_id: 4},
    {song_id: 96, setlist_id: 4},
    {song_id: 97, setlist_id: 4},
    {song_id: 98, setlist_id: 5},
    {song_id: 99, setlist_id: 5},
    {song_id: 100, setlist_id: 5},
    {song_id: 101, setlist_id: 5},
    {song_id: 102, setlist_id: 5},
    {song_id: 103, setlist_id: 5},
    {song_id: 104, setlist_id: 5},
    {song_id: 105, setlist_id: 5},
    {song_id: 106, setlist_id: 5},
    {song_id: 107, setlist_id: 5},
    {song_id: 108, setlist_id: 5},
    {song_id: 109, setlist_id: 5},
    {song_id: 110, setlist_id: 5},
    {song_id: 111, setlist_id: 5}
])
